package olsior.shop.telegram.domain;

public enum Position {
    ADD_PRODUCT,
    ADD_SHIRT,
    SIZE,
    STICKER,
    TWITCH_USERNAME,
    PLACE,
    DELIVERY,
    COUNTRY,
    FULL_NAME,
    ADDRESS,
    NO_SIZE,
    POST_OFFICE,
    PHONE_NUMBER,
    EMAIL,
    PAYMENT_CONFIRM,
    INFO_ABOUT_DELIVERY,
    PAYMENT_METHOD,
    CONFIRMATION,
    FOP_PAYMENT,
    ONLINE_PAYMENT,
    PAYMENT_CONFIRMATION,
    PROBLEM,
    USER_ID,
    MESSAGE_TO_USER,
    NONE
}
